### PR TITLE
Switch to using JLLs

### LINKED ISSUE #1: Add a BinaryBuilder for Normaliz
... so that people can use Normaliz.jl w/o compiling it; and so that installation is super fast.

This binarybuilder then could possibly also used by GAP.jl, for the GAP package `NormalizInterface`. 

It could then also leverage existing BinaryBuilders for flint, GMP, etc (maybe for arb, e-antic, cocoa, nauty, one should add separate BinaryBuilder, too...)

### LINKED ISSUE #2: Add CI tests (via GitHub Actions) and Codecov integration

### LINKED ISSUE #5: Add `[compat]` section to Project.toml

### PR DESCRIPTION
**Pull request by fingolfin**
This is incomplete (it does not build !!!!), as e.g. I have not yet made any attempts to adapt to the newer CxxWrap; but at least it showcases how to start using normaliz_jll

Resolves #1.
Resolves #2.
Resolves #5.

Also subsumes and hence closes #17, closes #29, closes #30

### CODE REVIEW

**Comment by w-bruns** [comment]
I have had a short look at the cjanges to normaliz.cpp. The existence of "renf support" is indicated by the the preprocessor variable ENFNORMALIZ. If one builds Normaliz via autotools, it is set in nmz_config.h by configure. This mechanism is used by PyNormaliz. The other optional packages are handled similarly.

**Comment by fingolfin** [comment]
Excellent. For the record, that's what is in `nmz_config.h` from `normaliz_jll` right now:
```
#undef ENFNORMALIZ
#undef NMZ_HASHLIBRARY
#undef NMZ_NAUTY
#undef NMZ_NAUTYNAUTY
#undef NMZ_NAUTY_TLS
#undef NMZ_FLINT
#undef NMZ_COCOA



#define NMZ_NAUTY
#define NMZ_NAUTYNAUTY

#define NMZ_FLINT

#define NORMALIZ_USE_DLL
```

I notice that this PR actually compiles in CI (it fails a bit later, in the "install" step but that's because I've not even touched that bit yet, I don't think it'll be a problem). Anyway, it doesn't compile on my mac, and I think that's because certain types are `typedef`'ed differently on macOS and Linux. I'll try to figure it out.

**Comment by fingolfin** [comment]
For the record, that's the error I get:
```
    Building Normaliz → `~/Projekte/OSCAR/Normaliz.jl/deps/build.log`
ERROR: Error building `Normaliz`, showing the last 100 of log:
  ^
/Users/mhorn/.julia/artifacts/4963e79493c4861f577fe7cc50f940bf7c15d1a7/include/gmpxx.h:1646:3: note: candidate constructor
/Users/mhorn/.julia/artifacts/4963e79493c4861f577fe7cc50f940bf7c15d1a7/include/gmpxx.h:1519:3: note: expanded from macro '__GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS'
  __gmp_expr(signed short int s) { init_si(s); }        \
  ^
/Users/mhorn/.julia/artifacts/4963e79493c4861f577fe7cc50f940bf7c15d1a7/include/gmpxx.h:1646:3: note: candidate constructor
/Users/mhorn/.julia/artifacts/4963e79493c4861f577fe7cc50f940bf7c15d1a7/include/gmpxx.h:1520:3: note: expanded from macro '__GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS'
  __gmp_expr(unsigned short int s) { init_ui(s); }      \
  ^
/Users/mhorn/.julia/artifacts/4963e79493c4861f577fe7cc50f940bf7c15d1a7/include/gmpxx.h:1646:3: note: candidate constructor
/Users/mhorn/.julia/artifacts/4963e79493c4861f577fe7cc50f940bf7c15d1a7/include/gmpxx.h:1521:3: note: expanded from macro '__GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS'
  __gmp_expr(signed long int l) { init_si(l); }         \
  ^
/Users/mhorn/.julia/artifacts/4963e79493c4861f577fe7cc50f940bf7c15d1a7/include/gmpxx.h:1646:3: note: candidate constructor
/Users/mhorn/.julia/artifacts/4963e79493c4861f577fe7cc50f940bf7c15d1a7/include/gmpxx.h:1522:3: note: expanded from macro '__GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS'
  __gmp_expr(unsigned long int l) { init_ui(l); }       \
  ^
/Users/mhorn/.julia/artifacts/4963e79493c4861f577fe7cc50f940bf7c15d1a7/include/gmpxx.h:1646:3: note: candidate constructor
/Users/mhorn/.julia/artifacts/4963e79493c4861f577fe7cc50f940bf7c15d1a7/include/gmpxx.h:1523:3: note: expanded from macro '__GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS'
  __gmp_expr(float f) { init_d(f); }                    \
  ^
/Users/mhorn/.julia/artifacts/4963e79493c4861f577fe7cc50f940bf7c15d1a7/include/gmpxx.h:1646:3: note: candidate constructor
/Users/mhorn/.julia/artifacts/4963e79493c4861f577fe7cc50f940bf7c15d1a7/include/gmpxx.h:1524:3: note: expanded from macro '__GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS'
  __gmp_expr(double d) { init_d(d); }
  ^
In file included from /Users/mhorn/Projekte/OSCAR/Normaliz.jl/deps/src/normaliz.cpp:8:
In file included from /Users/mhorn/.julia/artifacts/0cf36f0e1bb093f2b1bdfab1d1a2b92cb4de8cd8/include/jlcxx/jlcxx.hpp:15:
/Users/mhorn/.julia/artifacts/0cf36f0e1bb093f2b1bdfab1d1a2b92cb4de8cd8/include/jlcxx/module.hpp:123:20: error: call to constructor of '__gmp_expr<mpz_t, mpz_t>' is ambiguous
  T* cpp_obj = new T(std::forward<ArgsT>(args)...);
                   ^ ~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/mhorn/.julia/artifacts/0cf36f0e1bb093f2b1bdfab1d1a2b92cb4de8cd8/include/jlcxx/module.hpp:562:168: note: in instantiation of function template specialization 'jlcxx::create<__gmp_expr<mpz_t, mpz_t>, false, long long &>' requested here
    FunctionWrapperBase &new_wrapper = finalize ? method("dummy", [](ArgsT... args) { return create<T, true>(args...); }) : method("dummy", [](ArgsT... args) { return create<T, false>(args...); });
                                                                                                                                                                       ^
/Users/mhorn/.julia/artifacts/0cf36f0e1bb093f2b1bdfab1d1a2b92cb4de8cd8/include/jlcxx/module.hpp:986:16: note: in instantiation of function template specialization 'jlcxx::Module::constructor<__gmp_expr<mpz_t, mpz_t>, long long>' requested here
      m_module.constructor<T, ArgsT...>(m_dt, finalize);
               ^
/Users/mhorn/Projekte/OSCAR/Normaliz.jl/deps/src/normaliz.cpp:92:10: note: in instantiation of function template specialization 'jlcxx::TypeWrapper<__gmp_expr<mpz_t, mpz_t>>::constructor<long long>' requested here
        .constructor<int64_t>()
         ^
/Users/mhorn/.julia/artifacts/4963e79493c4861f577fe7cc50f940bf7c15d1a7/include/gmpxx.h:1646:3: note: candidate constructor
  __GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS
  ^
/Users/mhorn/.julia/artifacts/4963e79493c4861f577fe7cc50f940bf7c15d1a7/include/gmpxx.h:1515:3: note: expanded from macro '__GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS'
  __gmp_expr(signed char c) { init_si(c); }             \
  ^
/Users/mhorn/.julia/artifacts/4963e79493c4861f577fe7cc50f940bf7c15d1a7/include/gmpxx.h:1646:3: note: candidate constructor
/Users/mhorn/.julia/artifacts/4963e79493c4861f577fe7cc50f940bf7c15d1a7/include/gmpxx.h:1516:3: note: expanded from macro '__GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS'
  __gmp_expr(unsigned char c) { init_ui(c); }           \
  ^
/Users/mhorn/.julia/artifacts/4963e79493c4861f577fe7cc50f940bf7c15d1a7/include/gmpxx.h:1646:3: note: candidate constructor
/Users/mhorn/.julia/artifacts/4963e79493c4861f577fe7cc50f940bf7c15d1a7/include/gmpxx.h:1517:3: note: expanded from macro '__GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS'
  __gmp_expr(signed int i) { init_si(i); }              \
  ^
/Users/mhorn/.julia/artifacts/4963e79493c4861f577fe7cc50f940bf7c15d1a7/include/gmpxx.h:1646:3: note: candidate constructor
/Users/mhorn/.julia/artifacts/4963e79493c4861f577fe7cc50f940bf7c15d1a7/include/gmpxx.h:1518:3: note: expanded from macro '__GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS'
  __gmp_expr(unsigned int i) { init_ui(i); }            \
  ^
/Users/mhorn/.julia/artifacts/4963e79493c4861f577fe7cc50f940bf7c15d1a7/include/gmpxx.h:1646:3: note: candidate constructor
/Users/mhorn/.julia/artifacts/4963e79493c4861f577fe7cc50f940bf7c15d1a7/include/gmpxx.h:1519:3: note: expanded from macro '__GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS'
  __gmp_expr(signed short int s) { init_si(s); }        \
  ^
/Users/mhorn/.julia/artifacts/4963e79493c4861f577fe7cc50f940bf7c15d1a7/include/gmpxx.h:1646:3: note: candidate constructor
/Users/mhorn/.julia/artifacts/4963e79493c4861f577fe7cc50f940bf7c15d1a7/include/gmpxx.h:1520:3: note: expanded from macro '__GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS'
  __gmp_expr(unsigned short int s) { init_ui(s); }      \
  ^
/Users/mhorn/.julia/artifacts/4963e79493c4861f577fe7cc50f940bf7c15d1a7/include/gmpxx.h:1646:3: note: candidate constructor
/Users/mhorn/.julia/artifacts/4963e79493c4861f577fe7cc50f940bf7c15d1a7/include/gmpxx.h:1521:3: note: expanded from macro '__GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS'
  __gmp_expr(signed long int l) { init_si(l); }         \
  ^
/Users/mhorn/.julia/artifacts/4963e79493c4861f577fe7cc50f940bf7c15d1a7/include/gmpxx.h:1646:3: note: candidate constructor
/Users/mhorn/.julia/artifacts/4963e79493c4861f577fe7cc50f940bf7c15d1a7/include/gmpxx.h:1522:3: note: expanded from macro '__GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS'
  __gmp_expr(unsigned long int l) { init_ui(l); }       \
  ^
/Users/mhorn/.julia/artifacts/4963e79493c4861f577fe7cc50f940bf7c15d1a7/include/gmpxx.h:1646:3: note: candidate constructor
/Users/mhorn/.julia/artifacts/4963e79493c4861f577fe7cc50f940bf7c15d1a7/include/gmpxx.h:1523:3: note: expanded from macro '__GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS'
  __gmp_expr(float f) { init_d(f); }                    \
  ^
/Users/mhorn/.julia/artifacts/4963e79493c4861f577fe7cc50f940bf7c15d1a7/include/gmpxx.h:1646:3: note: candidate constructor
/Users/mhorn/.julia/artifacts/4963e79493c4861f577fe7cc50f940bf7c15d1a7/include/gmpxx.h:1524:3: note: expanded from macro '__GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS'
  __gmp_expr(double d) { init_d(d); }
  ^
4 errors generated.
make[2]: *** [CMakeFiles/normaliz_julia.dir/normaliz.cpp.o] Error 1
make[1]: *** [CMakeFiles/normaliz_julia.dir/all] Error 2
make: *** [all] Error 2
ERROR: LoadError: failed process: Process(`/Users/mhorn/.julia/packages/CMake/ULbyn/deps/usr/bin/cmake --build build --config Release --target install -- -j5`, ProcessExited(2)) [2]

Stacktrace:
 [1] pipeline_error
   @ ./process.jl:531 [inlined]
 [2] run(::Cmd; wait::Bool)
   @ Base ./process.jl:446
 [3] run(::Cmd)
   @ Base ./process.jl:444
 [4] top-level scope
   @ ~/Projekte/OSCAR/Normaliz.jl/deps/build.jl:73
 [5] include(fname::String)
   @ Base.MainInclude ./client.jl:451
 [6] top-level scope
   @ none:5
in expression starting at /Users/mhorn/Projekte/OSCAR/Normaliz.jl/deps/build.jl:73

Full log at /Users/mhorn/Projekte/OSCAR/Normaliz.jl/deps/build.log
```

The problem is that gmpxx does this:
```C++

#define __GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS		\
  __gmp_expr(signed char c) { init_si(c); }		\
  __gmp_expr(unsigned char c) { init_ui(c); }		\
  __gmp_expr(signed int i) { init_si(i); }		\
  __gmp_expr(unsigned int i) { init_ui(i); }		\
  __gmp_expr(signed short int s) { init_si(s); }	\
  __gmp_expr(unsigned short int s) { init_ui(s); }	\
  __gmp_expr(signed long int l) { init_si(l); }		\
  __gmp_expr(unsigned long int l) { init_ui(l); }	\
  __gmp_expr(float f) { init_d(f); }			\
  __gmp_expr(double d) { init_d(d); }
```
But then we give it arguments of type `long long`... and it can't decide what it should convert them to ("of course" `signed long int` would be the "natural" fit, as both are the same size; but they are not *identical*, and so by the C++ rules this is ambiguous). I am not completely sure why it works on Linux... it might also be a clang versus gcc thing.

Anyway, I also can't simply drop `long long`, as Normaliz uses this *everywhere* **sigh**.

So I guess I'll have to rev up my rusty C++ skills, and take a look what the proper way around it is. CxxWrap may also offer facilities for it.

**Comment by fingolfin** [comment]
This works now on macOS. On Linux it crashes:
```
julia> xx = Normaliz.NmzMatrix{Normaliz.NmzRational}([1 2 ; 3 5])
2×2 Normaliz.NmzMatrixAllocated{Normaliz.NmzRational}:
 1  2
 3  5

julia> yy = Normaliz.LongCone( Dict( :cone => xx ) )
Normaliz cone

julia> Normaliz.get_matrix_cone_property( yy, "ExtremeRays" )
julia: libnormaliz/cone.cpp:7731: void libnormaliz::Cone<Integer>::try_Hilbert_Series_from_lattice_points(const libnormaliz::ConeProperties&) [with Integer = long int]: Assertion `false' failed.

signal (6): Aborted
in expression starting at REPL[3]:1
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x7fb8b9770728)
__assert_fail at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
try_Hilbert_Series_from_lattice_points at /workspace/srcdir/normaliz-3.9.3/source/libnormaliz/cone.cpp:7731
compute at /workspace/srcdir/normaliz-3.9.3/source/libnormaliz/cone.cpp:4027
compute at /workspace/srcdir/normaliz-3.9.3/source/libnormaliz/cone.cpp:3575
getExtremeRaysMatrix at /workspace/srcdir/normaliz-3.9.3/source/libnormaliz/cone.cpp:2267
getMatrixConePropertyMatrix at /workspace/srcdir/normaliz-3.9.3/source/libnormaliz/cone.cpp:8419
...
```

I think this might be a problem in the current Normaliz_jll resp. in Normaliz 3.9.3 (the version currently in the JLL)   when using a `Cone<long>` instead of a `Cone<long long>`....

I'll try to fix this by switching to `Cone<long long>`

**Pull request merged**
