### PR TITLE
Set up basic CI tests

### LINKED ISSUE #2: Add CI tests (via GitHub Actions) and Codecov integration

### PR DESCRIPTION
**Pull request by fingolfin**
Resolves #2

### CODE REVIEW

**Comment by fingolfin** [comment]
@w-bruns so this is chugging along, but of course it takes quite some time to compile all. With my other PR, there is almost zero compilation time... Still, even without it, we could make things faster. E.g. I could set things up so that `ccache` is used to cache the C++ compiler results, that usually gives a dramatic speed up. Alas, that only makes sense if we don't use the JLL approach... *shrug*

**Comment by fingolfin** [comment]
Note that after ~10 minutes, it's in still in the middle of building FLINT... But we could use a mixed approach, too: take GMP, FMPR, FLINT, ... from the JLLs, but build e-antic, normaliz from source. But again: investing work into that doesn't seem so useful for me, as I really believe the way forward is with JLLs.

**Comment by fingolfin** [comment]
I've updated this, but it fails building with some C++ errors, probably because something changed on the Normaliz side and we need to adapt...

@w-bruns I see two ways forward with this PR:
1. instead of using the latest Normaliz master, I could point it at a specific older version, that might also solve the compilation issue for now (and would avoid random future breakages)
2. analyze the C++ compiler errors and adjust the C++ code in this repository (probably what we need to do long term).

Any thoughts on this?

Note that this PR is just a stepping stone towards a future using JLLs (i.e. using precompiled Normaliz binaries), see PR #9 -- but I think it makes sense to first get what we have already working again, and only then attempt the switch to JLLs.

**Comment by w-bruns** [comment]
As far as I can see there are mainly (perhaps: only) errors related to e-antic. e-antic has undergone substantial changes after the present interface was written. Normaliz and PyNormaliz work with the new version, the Julia code most likely not. 

In the Normaliz API there has been only one change that is not backward compatible: the function getGenerators, getGeneratorsMatrix, getNrGenerators don't exist anymore. That many functions have been added, should not be a problem.

**Comment by w-bruns** [comment]
It is not clear to me whether simpler number formats, long long por mpz_class,  would work already.

**Comment by saraedum** [comment]
@w-bruns you wrote me an email. I guess that's the PR that you were referring to?

I am not sure what's the kind of input that you'd like to see here.

```
 error: ambiguous overload for ‘operator=’ (operand types are ‘eantic::renf_elem_class’ and ‘fmpq_poly_t’ {aka ‘fmpq_poly_struct [1]’})
```

I think this is one is trying to use a constructor that converted a constant polynomial over the rationals into a number field element. That constructor was removed. The solution here would be to explicitly get the constant coefficient.

```
error: no matching function for call to ‘eantic::renf_class::renf_class(std::__cxx11::basic_string<char>&, std::__cxx11::basic_string<char>&, std::__cxx11::basic_string<char>&)’
```

The problem here is that `renf_class` has no public constructors anymore. To fix memory issues, all the construction needs to go through `renf_class::make`: https://github.com/flatsurf/e-antic/blob/master/libeantic/e-antic/renf_class.hpp#L102

**Comment by fingolfin** [comment]
@saraedum thanks that actually sounds quite helpful! @w-bruns is now visiting me in Kaiserslautern and we'll try to make this package work again (ideally with an without JLLs)

**Comment by fingolfin** [comment]
We decided to merge this as-is for now, and then we can continue work based on this.

**Pull request merged**
